Fix VariableDoesNotExist exceptions
jazzband/django-constance pull request #587
Opened 2024-09-14 03:28 UTC by spiceworm

These were being thrown if fieldsets and subtitle
are missing from the context.

This commit fixes #586

2024-09-16 08:45 UTC, Mogost requested changes
Django's template processor shouldn't raise an exception if a variable is missing.

2024-09-18 18:48 UTC, spiceworm commented
The exception does not halt execution, but it does appear in the DEBUG logs.

```
In [1]: from django.http import HttpRequest                                                                                                                       
   ...: from django.template import Template, RequestContext                                                                                                      
   ...:                                                                                                                                                           
   ...: request = HttpRequest()                                                                                                                                   
   ...: request.method = 'GET'                                                                                                                                    
   ...: request.META = {}                                                                                                                                            ...: request.META['SERVER_NAME'] = 'localhost'                                                                                                                 
                                        
In [2]: template = Template("This is a test {{ var_does_not_exist }}")
   ...: context = RequestContext(request)                                                                                                                         
   ...: template.render(context)
DEBUG 2024-09-18 18:46:20,401 base 216 139496148310912 Exception while resolving variable 'var_does_not_exist' in template 'unknown'.
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 883, in _resolve_lookup
    current = current[bit]
              ~~~~~~~^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/context.py", line 85, in __getitem__
    raise KeyError(key)
KeyError: 'var_does_not_exist'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 889, in _resolve_lookup
    if isinstance(current, BaseContext) and getattr(
                                            ^^^^^^^^
AttributeError: type object 'RequestContext' has no attribute 'var_does_not_exist'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 899, in _resolve_lookup
    current = current[int(bit)]
                      ^^^^^^^^
ValueError: invalid literal for int() with base 10: 'var_does_not_exist'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 906, in _resolve_lookup
    raise VariableDoesNotExist(
django.template.base.VariableDoesNotExist: Failed lookup for key [var_does_not_exist] in [{'True': True, 'False': False, 'None': None}, {'csrf_token': <SimpleLazy
Object: <function csrf.<locals>._get_val at 0x7edef47f9300>>, 'request': <HttpRequest>, 'user': <django.contrib.auth.models.AnonymousUser object at 0x7edef4307ce0
>, 'perms': PermWrapper(<django.contrib.auth.models.AnonymousUser object at 0x7edef4307ce0>), 'messages': [], 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 
'SUCCESS': 25, 'WARNING': 30, 'ERROR': 40}}, {}]
Out[2]: 'This is a test '
```

2024-09-18 19:48 UTC, Mogost commented
The behavior you're showing is typical for Django. If logs are too noisy, you can adjust the logging configuration. Missing context in Django templates is not an issue - `{% if something %}` works whether the variable exists or not, and both cases are handled safely.

For django-constance, tracking all possible context variables would add unnecessary maintenance overhead.

2024-10-28 19:35 UTC, camilonova commented
I'm closing this. I think it is not necessary.

2024-10-28 19:35 UTC, closed without merging